# Site settings
title: Java Usergroup Augsburg
email: info@jug-augsburg.de
description: > 
  Java Usergroup Augsburg: Infos, Veranstaltungen und Hintergründe.
  Wir sind eine Gruppe unabhängiger Java-Programmierer, die Spaß
  an gemeinsamer Fortbildung haben.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://convien.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
